/** Local feasibility helper for the future D1 operation; not wired to Worker routes. */
export const CONSUME_CHALLENGE_SQL = `UPDATE auth_challenges
  SET consumed_at = ?
  WHERE challenge_id = ?
    AND nonce_sha256 = ?
    AND device_id = ?
    AND credential_id = ?
    AND credential_version = ?
    AND consumed_at IS NULL
    AND expires_at > ?`;

export interface ChallengeConsumeDatabase {
  prepare(sql: string): {
    bind(...values: (string | number)[]): {
      run(): Promise<{ success: boolean; meta?: { changes?: number } }>;
    };
  };
}

export interface ChallengeConsumeInput {
  challengeId: string;
  nonceSha256: string;
  deviceId: string;
  credentialId: string;
  credentialVersion: number;
  serverNowUtc: string;
}

export type ChallengeConsumeResult = "consumed" | "rejected" | "invalid";

const identifier = (value: string) => /^[A-Za-z0-9_-]{8,80}$/.test(value);
const instant = (value: string) => /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value) &&
  Number.isFinite(Date.parse(value)) && new Date(value).toISOString() === value;

/**
 * Call only after verifying the signed request against the selected challenge.
 * serverNowUtc must be generated by the Worker immediately before this call,
 * never taken from a controller header/body. One conditional UPDATE is the
 * authoritative compare-and-consume operation; a loser changes zero rows.
 */
export async function consumeChallenge(db: ChallengeConsumeDatabase, input: ChallengeConsumeInput): Promise<ChallengeConsumeResult> {
  if (!identifier(input.challengeId) || !/^[a-f0-9]{64}$/.test(input.nonceSha256) ||
      !identifier(input.deviceId) || !identifier(input.credentialId) ||
      !Number.isSafeInteger(input.credentialVersion) || input.credentialVersion < 1 || !instant(input.serverNowUtc)) {
    return "invalid";
  }
  const result = await db.prepare(CONSUME_CHALLENGE_SQL)
    .bind(input.serverNowUtc, input.challengeId, input.nonceSha256, input.deviceId,
      input.credentialId, input.credentialVersion, input.serverNowUtc)
    .run();
  return result.success && result.meta?.changes === 1 ? "consumed" : "rejected";
}
